// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaytbzwfysmjqsvdgfaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVheXRiendmeXNtanFzdmRnZmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTQ3MjcsImV4cCI6MjA1ODc5MDcyN30.I_WxUCbEnTfnsDTv98FJOZJUNDfdoy-CBE94TB80WcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);